services:
  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5433:5432"  # Expose PostgreSQL on port 5433 (host) to port 5432 (container)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_django
    ports:
      - "8000:8000"  # Expose the web container on port 8000 (both container and host)
    env_file:
      - .env
    volumes:
      - .:/app
      - ./staticfiles:/app/staticfiles   # BU QATORNI QO‘SHING
      - ./media:/app/media
    depends_on:
      - db
    networks:
      - app_network
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    networks:
      - app_network

volumes:
  postgres_data:

networks:
  app_network:
    driver: bridge