#services:
#  db:
#    image: postgres:15
#    container_name: postgres_db
#    env_file:
#      - .env
#    ports:
#      - "5433:5432"
#    volumes:
#      - postgres_data:/var/lib/postgresql/data
#    networks:
#      - app_network
#
#  web:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    container_name: web_django
#    ports:
#      - "8000:8000"
#    env_file:
#      - .env
#    volumes:
#      - .:/app
#    depends_on:
#      - db
#    networks:
#      - app_network
#
#  nginx:
#    build:
#      context: ./nginx
#      dockerfile: Dockerfile.nginx
#    container_name: django_practise_nginx
#    ports:
#      - "8080:80"
#      - "443:443"
#    volumes:
#      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
#    depends_on:
#      - web
#    networks:
#      - app_network
#
#networks:
#  app_network:
#    driver: bridge
#volumes:
#  postgres_data:

services:
  db:
    image: postgres:15
    container_name: postgres_db
    env_file:
      - .env
    ports:
      - "5433:5432"  # Expose PostgreSQL on port 5433 (host) to port 5432 (container)
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web_django
    ports:
      - "8000:8000"  # Expose the web container on port 8000 (both container and host)
    env_file:
      - .env
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - app_network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    container_name: django_practise_nginx
    ports:
      - "8080:80"   # Expose Nginx on port 8080 of the host machine (mapped from port 80 inside the container)
      - "443:443"   # Expose port 443 for HTTPS (this should be configured for SSL)
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
